/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aroundtheworld

fun main() {
    println("Hello World!")

    var cuba = Country("Cuba")
    println(cuba.name)
    println(cuba.longitude)
    println(cuba.latitude)
    println(cuba.currencyCodes())
    println(cuba.neighbors())

    println("Goodbye World!")
}
